sudo:required
services:
  - docker

before_install:
  - docker build -t jjapp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jjapp/docker-react npm run test

  -- added comment by jyoti testing
